# Generated by Django 6.1.1 on 2026-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="advance_payments",
            field=models.JSONField(default=list),
        ),
    ]
