# Generated by Django 5.2.15 on 2026-07-02 18:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Co2Factor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("energy_type", models.TextField()),
                (
                    "factor_kg_per_unit",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("unit", models.TextField()),
                ("source", models.TextField(default="")),
                ("source_url", models.TextField(blank=True, null=True)),
                ("valid_from", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "co2_factors",
                "ordering": ["energy_type", "-valid_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "energy_type", "valid_from"),
                        name="uq_co2_user_type_date",
                    )
                ],
            },
        ),
    ]
