[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:nginx]
command=nginx -g "daemon off;"
priority=10
autostart=true
autorestart=true
stopsignal=SIGQUIT
stopwaitsecs=15
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gunicorn]
command=gunicorn config.wsgi:application --bind 127.0.0.1:8000 --workers %(ENV_GUNICORN_WORKERS)s --access-logfile - --error-logfile -
directory=/app
user=appuser
environment=HOME="/home/appuser",DJANGO_SETTINGS_MODULE="config.settings.prod"
priority=20
autostart=true
autorestart=true
stopsignal=SIGTERM
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
